config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'


  resources :cars do
    resources :reviews
    resources :favorites
  end
  get 'cars/filter/:scope' => "cars#index", as: :filtered_cars
  resources :users
  get 'signup' => 'users#new'
  get 'signin' => "sessions#new"
  resource :session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  self.inheritance_column = nil
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  TYPES = %w(Sedan SUV Hatchback Coupe Hybrid)
  # def to_param
  # "#{id}-#{make.parameterize}"
  # end
  scope :recent, ->{ where('mileage < 1000') }

  scope :used, ->{ where('mileage >= 1000') }

  scope :sedan, ->{ where(type: 'Sedan')}

  scope :suv, ->{ where(type: 'SUV') }

  scope :hatchback, ->{ where(type: 'Hatchback') }

  scope :coupe, ->{ where(type: 'Coupe') }

  scope :hybrid, ->{ where(type: 'Hybrid') }


  def self.recently_added
  order('created_at desc').limit(3)
  end

  def average_stars
    reviews.average(:stars)
  end

  def recent_reviews
    reviews.order('created_at desc').limit(2)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :comment, length: { minimum: 4 }

STARS = [1, 2, 3, 4, 5]

validates :stars, inclusion: {
  in: STARS,
  message: "must be between 1 and 5"
}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

has_many :reviews, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :favorite_cars, through: :favorites, source: :car

validates :name, presence: true

validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }

def self.authenticate(email, password)
  user = User.find_by(email: email)
  user && user.authenticate(password)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    case params[:scope]
      when 'sedan'
        @cars = Car.sedan
      when 'suv'
        @cars = Car.suv
      when 'hatchback'
        @cars = Car.hatchback
      when 'coupe'
        @cars = Car.coupe
      when 'hybrid'
        @cars = Car.hybrid
      when 'recent'
        @cars = Car.recent
      when 'used'
        @cars = Car.used
      else
        @cars = Car.all
    end
  end

  def show
    @car = Car.find(params[:id])
    if current_user
      @current_favorite = current_user.favorites.find_by(car_id: @car.id)
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to @car
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    redirect_to @car
  end


private
def car_params
  params.require(:car).permit(:make, :model, :year, :price, :color, :description, :mileage, :image_file_name, :type)
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @car.favorites.create!(user: current_user)
    redirect_to @car, notice: "This #{@car.model} was added to your favorites!"
  end

  def destroy
    @car = Car.find(params[:car_id])
    favorite = current_user.favorites.find(params[:id])
    favorite.destroy
    redirect_to @car, notice: "This #{@car.model} has been removed from your favorites."
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_signin
  before_action :set_car

  def index
    @reviews = @car.reviews
  end

  def new
    @review = @car.reviews.new
  end

  def create
    @review = @car.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to car_reviews_path(@car), notice: "Thank you for reviewing."
    else
      render :new
    end
  end


  def destroy
    @review = @car.reviews.find(params[:id])
    @review.destroy
    redirect_to car_reviews_path(@car), notice: "Review removed!"
  end
end


private

def review_params
  params.require(:review).permit(:comment, :stars)
end

def set_car
  @car = Car.find(params[:car_id])
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Greetings, #{user.name}!"
      redirect_to(session[:intended_url] || user)
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Farewell!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_cars = @user.favorite_cars
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_url
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @cars = Car.limit(3).order("RANDOM()")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/cars_helper.rb
module CarsHelper

  def image_for(car)
    if car.image_file_name.blank?
      image_tag("placeholder.jpg")
    else
      image_tag(car.image_file_name)
    end
  end

  def price_for(car)
    if car.price.blank?
      "Make An Offer."
    else
      number_to_currency(car.price)
    end
  end

  def delete_review_image
    image_tag('trash.png', style: 'border: 0', title: 'Delete Review')
  end

  def format_average_stars(car)
    if car.average_stars.nil?
      content_tag(:strong, 'No reviews')
    else
      pluralize(number_with_precision(car.average_stars, :precision => 1) , 'star')
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
     <%= f.label :type, class: "col-md-2" %>
     <%= f.select :type, Car::TYPES, prompt: "Pick one", class: "col-md-10" %>
   </div>
  <div class="form-group">
    <%= f.label :make, class: "col-md-2" %>
    <%= f.text_field :make, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.label :model, class: "col-md-2" %>
    <%= f.text_field :model, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.label :year, class: "col-md-2" %>
    <%= f.number_field :year, class: "col-md-10" %>
  </div>
  <div class="form-group">
  <%= f.label :price, class: "col-md-2" %>
  <%= f.number_field :price, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.label :color, class: "col-md-2" %>
    <%= f.text_field :color, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.label :mileage, class: "col-md-2" %>
    <%= f.number_field :mileage, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-md-2" %>
    <%= f.text_area :description, cols: 40, rows: 7, class: "col-md-10"%>
  </div>
  <div class="form-group">
    <%= f.label :image_file_name, class: "col-md-2" %>
    <%= f.text_field :image_file_name, class: "col-md-10" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
    <%= link_to "Cancel", cars_path %>
  </div>
  <% end %>

app/views/cars/edit.html.erb
<h1>Editing Car: <%= "#{@car.make} #{@car.model}" %></h1>
<%= render 'form' %>

app/views/cars/index.html.erb
<% @cars.each do |car| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_for(car) %>
    </div>
    <div class="col-md-9">
      <h2><%= link_to("#{car.year} #{car.make} #{car.model}", car) %></h2>
      <h3><%= price_for(car) %></h3>
      <table class="table">
        <tr>
          <th>Color:</th>
          <td><%= car.color %></td>
        </tr>
        <tr>
          <th>Mileage:</th>
          <td><%= car.mileage %></td>
        </tr>
        <tr>
          <th>Description:</th>
          <td><%= truncate(car.description, length: 200, separator: ' ') %></td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/cars/new.html.erb
<h2>New Car <%= @car.make %></h2>
<%= render 'form' %>

app/views/cars/show.html.erb
<h2><%= "#{@car.year} #{@car.make} #{@car.model}" %></h2>

<div class="row">
  <div class="col-md-3 show">
    <%= image_for(@car) %>
  </div>
  <div class="col-md-9">
    <table class="show-page table">
      <tr>
        <th>Price:</th>
        <td><%= price_for(@car) %></td>
      </tr>
      <tr>
        <th>Mileage:</th>
        <td><%= @car.mileage %></td>
      </tr>
      <tr>
        <th>Color:</th>
        <td><%= @car.color %></td>
      </tr>
      <tr>
        <th>Description:</th>
        <td><%= @car.description %></td>
      </tr>
    </table>
  </div>
</div>

<% if current_user %>
  <% if @current_favorite %>
    <%= button_to "Dislike", car_favorite_path(@car, @current_favorite), method: :delete %>
  <% else %>
    <%= button_to "Like", car_favorites_path(@car) %>
  <% end %>
<% end %>

<h3>Average Review</h3>
<p>
  <%= format_average_stars(@car) %>
</p>

<h3>Reviews</h3>
<p>
  <%= link_to pluralize(@car.reviews.size, "review"),
              car_reviews_path(@car) %>
</p>
  <p>
    <%= link_to "Write Review", new_car_review_path(@car),
                class: 'button ok review' %>
  </p>

  <p>
    <% if current_user_admin? %>
      <%= link_to 'Edit', edit_car_path(@car), class: 'button' %>
      <%= link_to 'Delete', @car,
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2019
    <%= link_to 'Google', 'http://google.com' %>
  </p>
  <p>
    All Honda information sourced from Google searches completed by Megan, Kayla, and Nicole.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'BDS Hondas', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop By Type<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Shop Sedans", filtered_cars_path(:sedan) %></li>
              <li><%= link_to "Shop SUVS & Crossovers", filtered_cars_path(:suv) %></li>
              <li><%= link_to "Shop Coupes", filtered_cars_path(:coupe) %></li>
              <li><%= link_to "Shop Hatchbacks", filtered_cars_path(:hatchback) %></li>
              <li><%= link_to "Shop Hybrids & Electric", filtered_cars_path(:hybrid) %></li>
            </ul>
          </li>
          <li><%= link_to "View All New Inventory", filtered_cars_path(:recent) %></li>
          <li><%= link_to "View All Used Inventory", filtered_cars_path(:used) %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user_admin? %>
            <li><%= link_to "New", new_car_path(@car) %></li>
          <% end %>
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Account Details", current_user %></li>
                <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign Out", session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign Up', signup_path %></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BDS Honda's</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@car.title, @car) %></h1>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= link_to review.user.name, review.user %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <%= link_to delete_review_image, [@car, review],
                  id: "#{dom_id(review)}_delete",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to @car.make, @car %></h2>
</header>

<%= form_for [@car, @review] do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required stars">
        <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
          <span class="star">
            <%= f.radio_button :stars, star %> <%= star %>
          </span>
        <% end %>
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %>
      <%= link_to "Cancel", @car, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
  </header>

  <% if @reviews.any? %>
    <h3>Reviews</h3>
    <ol id="reviews">
     <% @reviews.each do |review| %>
       <li>
         <%= link_to review.car.title, review.car %>
         <span class="review"><%= pluralize(review.stars, 'star') %></span>
         <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
         <p>
           &quot;<%= review.comment %>&quot;
         </p>
       </li>
     <% end %>
    </ol>
  <% end %>

  <% if @favorite_cars.any? %>
  <h3>Favorite cars</h3>
  <ul>
   <% @favorite_cars.each do |car| %>
     <li>
       <%= link_to "#{car.year} #{car.model}", car %>
     </li>
   <% end %>
  </ul>
<% end %>

  <footer>
    <nav>
      <% if current_user?(@user) %>
        <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
        <%= link_to 'Delete Account', @user,
                    method: :delete,
                    data: { confirm: 'Are you sure you want to permanently delete your account?' },
                    class: 'button' %>
      <% end %>
    </nav>
  </footer>
</article>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome to <span class = "welcome">BDS Hondas</span></h1>
  <p>Formerly Known as "Mr. Hodges' Hondas". Now under new management!</p>
  <p>Check out our Featured Vehicles below!</p>
</div>
<div class="row welcome">
  <% @cars.each do |car| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="thumbnail-image">
          <%= image_for(car) %>
        </div>
        <div class="caption">
          <h3><%= link_to "#{car.year} #{car.model}", car %></h3>
        </div>
      </div>
    </div>
    <% end %>
  </div>